### PR TITLE
Fixed navigation bar in all the pages

### PR DESCRIPTION
**Pull request by mthprem**

### CODE REVIEW

**Comment by AyushP510** [comment]
Can you please squash your commits, let's just keep one commit per Merge Request. There are 2 commits with same title in your branch right now

**Review by AyushP510 — APPROVED** [review]
Looks good. But need to update bootstrap to 5.2 on all pages, just like on the index page. (Can be done separately)

**Comment by mthprem** [comment]
> Looks good. But need to update bootstrap to 5.2 on all pages, just like on the index page. (Can be done separately)

Yup. That sounds good and we also need to refactor the code as many of them are repeated.

**Comment by mthprem** [comment]
Please deploy it.

**Pull request merged**
